import { mutation } from "./_generated/server";

export const seedAll = mutation({
  args: {},
  handler: async (ctx) => {
    // 1. Site Settings
    const existingSettings = await ctx.db.query("siteSettings").first();
    if (!existingSettings) {
      await ctx.db.insert("siteSettings", {
        siteName: "TMS İTHALAT",
        slogan: "Türkiye'nin Oto Elektronik Parça Merkezi",
        whatsappNumber: "+905340653222",
        whatsappDisplay: "+90 534 065 32 22",
        phone: "+90 534 065 32 22",
        email: "info@tmsithalat.com",
        address: "Fevzipaşa Mh. 10121 Sk. No: 2 Karatay / KONYA",
        workingHours: "Pazartesi - Cumartesi: 08:30 - 19:00",
        announcement: "Türkiye'nin her yerine aynı gün hızlı kargo ve test garantisi!",
        heroHeadline: "Türkiye'nin Oto Elektronik Parça Merkezi",
        heroSubheadline: "ECU, ABS, Airbag, BCM, BSI, UCH ve binlerce orijinal elektronik modül.",
        stats: {
          productsCount: "15.000+",
          brandsCount: "45+",
          ecuCount: "1000+",
          experienceYears: "20+",
        },
      });
    }

    // 2. Clear old categories and seed fresh accurate categories
    const oldCategories = await ctx.db.query("categories").collect();
    for (const cat of oldCategories) {
      await ctx.db.delete(cat._id);
    }

    const categoriesList = [
      {
        name: "Motor Beyinleri (ECU)",
        slug: "motor-beyinleri-ecu",
        description: "Farklı marka ve modellere uygun çıkma ve sıfır motor beyinleri. Binlerce stoklu ürün, uygun fiyat ve garantili hizmet.",
        image: "/images/cat-ecu.jpg",
        order: 1,
        featured: true,
        itemCount: 324,
      },
      {
        name: "ABS / ESP Beyinleri",
        slug: "abs-esp-beyinleri",
        description: "Bosch, ATE ve TRW marka test edilmiş ABS ve ESP hidrolik beyin modülleri.",
        image: "/images/cat-abs.jpg",
        order: 2,
        featured: true,
        itemCount: 142,
      },
      {
        name: "Airbag Beyinleri",
        slug: "airbag-beyinleri",
        description: "Hava yastığı sensör ve tetikleme kontrol modülleri.",
        image: "/images/cat-airbag.jpg",
        order: 3,
        featured: true,
        itemCount: 98,
      },
      {
        name: "BCM / BSI Beyinleri",
        slug: "bcm-bsi-sam-modulleri",
        description: "Gövde kontrol modülleri, konfor ve aydınlatma beyinleri.",
        image: "/images/cat-bcm.jpg",
        order: 4,
        featured: true,
        itemCount: 86,
      },
      {
        name: "UCH / SAM Modülleri",
        slug: "uch-sam-modulleri",
        description: "Renault UCH ve Mercedes SAM merkezi elektronik sigorta kontrol üniteleri.",
        image: "/images/cat-uch.jpg",
        order: 5,
        featured: true,
        itemCount: 64,
      },
      {
        name: "Sigorta Kutuları",
        slug: "sigorta-kutulari",
        description: "Motor içi ve kabin içi sigorta röle dağıtım tablaları (BSM / UPC).",
        image: "/images/cat-fusebox.jpg",
        order: 6,
        featured: true,
        itemCount: 110,
      },
      {
        name: "Gösterge Panelleri",
        slug: "gosterge-panelleri",
        description: "Dijital ve analog gösterge kadranları, hız ve devir saatleri.",
        image: "/images/cat-cluster.jpg",
        order: 7,
        featured: true,
        itemCount: 75,
      },
      {
        name: "Direksiyon Kumanda Modülleri",
        slug: "direksiyon-kumanda-modulleri",
        description: "Direksiyon açı sensörleri, sargı ve sinyal kol kütükleri.",
        image: "/images/cat-steering.jpg",
        order: 8,
        featured: true,
        itemCount: 52,
      },
      {
        name: "Klima Kontrol Üniteleri",
        slug: "klima-kontrol-uniteleri",
        description: "Dijital klima panelleri, kalorifer ve AC kontrol düğmeleri.",
        image: "/images/cat-climate.jpg",
        order: 9,
        featured: true,
        itemCount: 45,
      },
      {
        name: "Multimedya Üniteleri",
        slug: "multimedya-uniteleri",
        description: "Orijinal araç içi ekran, navigasyon ve teyp üniteleri.",
        image: "/images/cat-multimedia.jpg",
        order: 10,
        featured: true,
        itemCount: 38,
      },
      {
        name: "Konfor Modülleri",
        slug: "konfor-modulleri",
        description: "Kapı, cam ve merkezi kilit konfor kontrol modülleri.",
        image: "/images/cat-comfort.jpg",
        order: 11,
        featured: true,
        itemCount: 40,
      },
      {
        name: "Şanzıman Beyinleri",
        slug: "sanziman-beyinleri",
        description: "DSG, EDC, 7G-Tronic ve otomatik şanzıman mekatronik kontrol beyinleri.",
        image: "/images/cat-transmission.jpg",
        order: 12,
        featured: true,
        itemCount: 65,
      },
    ];

    for (const c of categoriesList) {
      await ctx.db.insert("categories", c);
    }

    // 3. Seed Brands
    const oldBrands = await ctx.db.query("brands").collect();
    for (const b of oldBrands) {
      await ctx.db.delete(b._id);
    }

    const brandList = [
      { name: "Volkswagen", slug: "volkswagen", popular: true, order: 1 },
      { name: "Mercedes-Benz", slug: "mercedes-benz", popular: true, order: 2 },
      { name: "BMW", slug: "bmw", popular: true, order: 3 },
      { name: "Audi", slug: "audi", popular: true, order: 4 },
      { name: "Ford", slug: "ford", popular: true, order: 5 },
      { name: "Renault", slug: "renault", popular: true, order: 6 },
      { name: "Peugeot", slug: "peugeot", popular: true, order: 7 },
      { name: "Citroën", slug: "citroen", popular: true, order: 8 },
      { name: "Fiat", slug: "fiat", popular: true, order: 9 },
      { name: "Opel", slug: "opel", popular: true, order: 10 },
      { name: "Seat", slug: "seat", popular: true, order: 11 },
      { name: "Skoda", slug: "skoda", popular: true, order: 12 },
      { name: "Volvo", slug: "volvo", popular: true, order: 13 },
      { name: "Toyota", slug: "toyota", popular: true, order: 14 },
      { name: "Hyundai", slug: "hyundai", popular: true, order: 15 },
    ];

    for (const b of brandList) {
      await ctx.db.insert("brands", b);
    }

    // 4. Seed Rich Real Automotive Electronics Inventory
    const oldProducts = await ctx.db.query("products").collect();
    for (const p of oldProducts) {
      await ctx.db.delete(p._id);
    }

    const now = Date.now();
    const realInventory = [
      // 1. Bosch ECU Passat 2.0 TDI
      {
        title: "Bosch ECU VW Passat 2.0 TDI",
        slug: "0281011234-volkswagen-passat",
        oemNumber: "0281011234",
        boschNumber: "0281011234",
        otherNumbers: ["03L906022LF", "EDC17CP14", "03L906022MJ"],
        categorySlug: "motor-beyinleri-ecu",
        categoryName: "Motor Beyinleri (ECU)",
        brand: "Volkswagen",
        model: "Passat 2.0 TDI",
        generation: "B6 / B7",
        yearRange: "2010 - 2014",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "3 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "94 Pin",
        voltage: "12V",
        weight: "1.25 kg",
        dimensions: "18 x 16 x 4 cm",
        softwareVersion: "1037390232",
        hardwareVersion: "1037396123",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Bosch 0281011234 Motor Kontrol Ünitesi, Volkswagen Passat 2.0 TDI araçlar için üretilmiş orijinal ECU modülüdür. Tüm fonksiyonları test edilmiştir ve sorunsuz çalışmaktadır. İmmobilizer klonlama ve yazılım aktarım desteği ile birlikte sunulmaktadır.",
        images: ["/images/catalog-ecu-banner.jpg", "/images/cat-ecu.jpg", "/images/hero-ecu-modules.jpg"],
        compatibleVehicles: [
          { brand: "Volkswagen", model: "Passat", engine: "2.0 TDI", yearRange: "2010 - 2014", oemNumber: "0281011234" },
          { brand: "Volkswagen", model: "Passat CC", engine: "2.0 TDI", yearRange: "2009 - 2012", oemNumber: "0281011234" },
          { brand: "Volkswagen", model: "Tiguan", engine: "2.0 TDI", yearRange: "2010 - 2013", oemNumber: "0281011234" },
          { brand: "Volkswagen", model: "Sharan", engine: "2.0 TDI", yearRange: "2010 - 2014", oemNumber: "0281011234" },
        ],
        installationNotes: "Montaj öncesinde mutlaka akü eksi (-) kutbunu çıkarınız. Pin soketlerinin kilit mandalını tam oturtunuz.",
        featured: true,
        createdAt: now - 10000,
        updatedAt: now - 10000,
      },

      // 2. Mercedes W204 ECU
      {
        title: "Mercedes ECU W204 2.2 CDI",
        slug: "a6519005401-mercedes-w204",
        oemNumber: "A6519005401",
        boschNumber: "28286915",
        otherNumbers: ["A6519019400", "CRD2.30", "OM651"],
        categorySlug: "motor-beyinleri-ecu",
        categoryName: "Motor Beyinleri (ECU)",
        brand: "Mercedes-Benz",
        model: "C-Class W204 C220 CDI",
        generation: "W204 / S204",
        yearRange: "2011 - 2015",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "3 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "128 Pin",
        voltage: "12V",
        weight: "1.30 kg",
        dimensions: "19 x 16 x 4 cm",
        softwareVersion: "CRD2.30 OM651",
        hardwareVersion: "A6519019400",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Mercedes-Benz Delphi CRD2.30 Motor Kontrol Ünitesi, W204 C200/C220 CDI OM651 motorlar için orijinal çıkma ünitedir. Enjektör, DPF ve turbo aktüatör çıkışları simülatörde tam test edilmiştir.",
        images: ["/images/cat-ecu.jpg", "/images/catalog-ecu-banner.jpg"],
        compatibleVehicles: [
          { brand: "Mercedes-Benz", model: "C-Serisi W204", engine: "2.2 CDI OM651", yearRange: "2011 - 2015", oemNumber: "A6519005401" },
          { brand: "Mercedes-Benz", model: "E-Serisi W212", engine: "2.2 CDI OM651", yearRange: "2010 - 2014", oemNumber: "A6519005401" },
          { brand: "Mercedes-Benz", model: "GLK X204", engine: "2.2 CDI OM651", yearRange: "2011 - 2015", oemNumber: "A6519005401" },
        ],
        installationNotes: "SCN kodlama veya FBS3 immobilizer veri aktarımı gerekebilir. Teknik destek sağlanır.",
        featured: true,
        createdAt: now - 9000,
        updatedAt: now - 9000,
      },

      // 3. Bosch ECU Audi A3 2.0 TDI
      {
        title: "Bosch ECU Audi A3 2.0 TDI",
        slug: "03l906023lf-audi-a3",
        oemNumber: "03L906023LF",
        boschNumber: "0281017946",
        otherNumbers: ["EDC17C46", "03L906018LJ", "1037508930"],
        categorySlug: "motor-beyinleri-ecu",
        categoryName: "Motor Beyinleri (ECU)",
        brand: "Audi",
        model: "A3 2.0 TDI",
        generation: "8P",
        yearRange: "2008 - 2012",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "3 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "94 Pin",
        voltage: "12V",
        weight: "1.20 kg",
        dimensions: "18 x 16 x 4 cm",
        softwareVersion: "1037508930",
        hardwareVersion: "EDC17C46",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Bosch EDC17C46 Audi A3 ve TT 2.0 TDI motor beyni. Orijinal yazılımı ve kalibrasyonu korunmuş olup, doğrudan klonlanabilir ve tak-çalıştır hale getirilebilir.",
        images: ["/images/cat-ecu.jpg", "/images/catalog-ecu-banner.jpg"],
        compatibleVehicles: [
          { brand: "Audi", model: "A3 8P", engine: "2.0 TDI (CFFB/CFGB)", yearRange: "2008 - 2012", oemNumber: "03L906023LF" },
          { brand: "Seat", model: "Leon", engine: "2.0 TDI", yearRange: "2009 - 2012", oemNumber: "03L906023LF" },
          { brand: "Skoda", model: "Octavia", engine: "2.0 TDI", yearRange: "2009 - 2013", oemNumber: "03L906023LF" },
        ],
        installationNotes: "İmmobilizer kodlama için eski beyninizin gönderilmesi durumunda aynı gün birebir klonlama yapılır.",
        featured: true,
        createdAt: now - 8000,
        updatedAt: now - 8000,
      },

      // 4. Siemens SID807 Ford Focus 1.6 TDCi
      {
        title: "Siemens ECU Ford Focus 1.6 TDCi",
        slug: "5ws40539h-t-ford-focus",
        oemNumber: "5WS40539H-T",
        boschNumber: "AV61-12A650-CE",
        otherNumbers: ["SID807", "AV6112A650CE", "S180052028E"],
        categorySlug: "motor-beyinleri-ecu",
        categoryName: "Motor Beyinleri (ECU)",
        brand: "Ford",
        model: "Focus 1.6 TDCi",
        generation: "Focus 3",
        yearRange: "2011 - 2014",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "3 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "112 Pin",
        voltage: "12V",
        weight: "1.15 kg",
        dimensions: "17 x 15 x 3.5 cm",
        softwareVersion: "SID807-EVO",
        hardwareVersion: "AV61-12A650",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Continental / Siemens SID807 Ford Focus 3, C-Max ve Mondeo 1.6 TDCi (95/115 HP) motor kontrol modülü. Piezo enjektör sürücü katları test edilmiştir.",
        images: ["/images/cat-ecu.jpg", "/images/catalog-ecu-banner.jpg"],
        compatibleVehicles: [
          { brand: "Ford", model: "Focus 3", engine: "1.6 TDCi (T1DA/T3DA)", yearRange: "2011 - 2014", oemNumber: "5WS40539H-T" },
          { brand: "Ford", model: "C-Max", engine: "1.6 TDCi", yearRange: "2010 - 2015", oemNumber: "5WS40539H-T" },
          { brand: "Ford", model: "Grand C-Max", engine: "1.6 TDCi", yearRange: "2011 - 2014", oemNumber: "5WS40539H-T" },
        ],
        installationNotes: "PATS immobilizer tanıtımı veya full flash klonlama gerektirir.",
        featured: true,
        createdAt: now - 7000,
        updatedAt: now - 7000,
      },

      // 5. Continental SID305 Renault Megane 1.5 dCi
      {
        title: "Renault ECU Megane 1.5 dCi",
        slug: "237101702r-renault-megane",
        oemNumber: "237101702R",
        boschNumber: "S180067132A",
        otherNumbers: ["SID305", "237101736R", "237100483R"],
        categorySlug: "motor-beyinleri-ecu",
        categoryName: "Motor Beyinleri (ECU)",
        brand: "Renault",
        model: "Megane 1.5 dCi",
        generation: "Megane 3 / Fluence",
        yearRange: "2011 - 2015",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "3 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "112 Pin",
        voltage: "12V",
        weight: "1.10 kg",
        dimensions: "17 x 15 x 3.5 cm",
        softwareVersion: "SID305 V1.2",
        hardwareVersion: "237101702R",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Continental SID305 Renault Megane 3, Fluence ve Scenic 1.5 dCi K9K motorlar için orijinal çıkma beyin. Enjektör kodlama ve immobilizer virginleme seçeneği mevcuttur.",
        images: ["/images/cat-ecu.jpg", "/images/catalog-ecu-banner.jpg"],
        compatibleVehicles: [
          { brand: "Renault", model: "Megane 3", engine: "1.5 dCi (K9K)", yearRange: "2011 - 2015", oemNumber: "237101702R" },
          { brand: "Renault", model: "Fluence", engine: "1.5 dCi (K9K)", yearRange: "2010 - 2016", oemNumber: "237101702R" },
          { brand: "Renault", model: "Scenic 3", engine: "1.5 dCi (K9K)", yearRange: "2011 - 2015", oemNumber: "237101702R" },
        ],
        installationNotes: "Virginlenmiş olarak gönderilebilir veya doğrudan klonlama yapılabilir.",
        featured: true,
        createdAt: now - 6000,
        updatedAt: now - 6000,
      },

      // 6. Bosch MED17 Audi A4 2.0 TFSI
      {
        title: "Audi ECU A4 2.0 TFSI",
        slug: "8k0907115d-audi-a4",
        oemNumber: "8K0907115D",
        boschNumber: "0261S04344",
        otherNumbers: ["MED17.5", "8K09907115", "1037397821"],
        categorySlug: "motor-beyinleri-ecu",
        categoryName: "Motor Beyinleri (ECU)",
        brand: "Audi",
        model: "A4 2.0 TFSI",
        generation: "B8",
        yearRange: "2010 - 2014",
        fuelType: "Benzin",
        condition: "Çıkma - Orijinal",
        warranty: "3 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "128 Pin",
        voltage: "12V",
        weight: "1.35 kg",
        dimensions: "19 x 16 x 4 cm",
        softwareVersion: "MED17.5 1037397821",
        hardwareVersion: "8K0907115D",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Bosch MED17.5 Audi A4 B8, A5 ve Q5 2.0 TFSI motor kontrol ünitesi. Yüksek basınç yakıt pompası ve doğrudan enjeksiyon katları test edilmiştir.",
        images: ["/images/cat-ecu.jpg", "/images/catalog-ecu-banner.jpg"],
        compatibleVehicles: [
          { brand: "Audi", model: "A4 B8", engine: "2.0 TFSI (CDNC)", yearRange: "2010 - 2014", oemNumber: "8K0907115D" },
          { brand: "Audi", model: "A5", engine: "2.0 TFSI", yearRange: "2009 - 2013", oemNumber: "8K0907115D" },
          { brand: "Audi", model: "Q5", engine: "2.0 TFSI", yearRange: "2010 - 2014", oemNumber: "8K0907115D" },
        ],
        installationNotes: "İmmobilizer uyarlaması ODIS Online veya BDM klonlama ile yapılmalıdır.",
        featured: true,
        createdAt: now - 5000,
        updatedAt: now - 5000,
      },

      // 7. Magneti Marelli MJD Fiat Doblo 1.3 Multijet
      {
        title: "Bosch / Marelli ECU Fiat Doblo 1.3 Multijet",
        slug: "0281031679-fiat-doblo",
        oemNumber: "0281031679",
        boschNumber: "51843360",
        otherNumbers: ["MJD 6F3.D4", "51843360", "MJD6F3D4"],
        categorySlug: "motor-beyinleri-ecu",
        categoryName: "Motor Beyinleri (ECU)",
        brand: "Fiat",
        model: "Doblo 1.3 Multijet",
        generation: "Doblo 3 / Fiorino",
        yearRange: "2010 - 2014",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "3 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "94 Pin",
        voltage: "12V",
        weight: "1.05 kg",
        dimensions: "16 x 14 x 3.5 cm",
        softwareVersion: "MJD6F3.D4/HW04P",
        hardwareVersion: "51843360",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Magneti Marelli MJD 6F3 Fiat Doblo, Fiorino ve Linea 1.3 Multijet motor beyni. İmmobilizer sıfırlanmış (Virgin) olarak tak-çalıştır teslim edilir.",
        images: ["/images/cat-ecu.jpg", "/images/catalog-ecu-banner.jpg"],
        compatibleVehicles: [
          { brand: "Fiat", model: "Doblo", engine: "1.3 Multijet 75/90 HP", yearRange: "2010 - 2014", oemNumber: "0281031679" },
          { brand: "Fiat", model: "Fiorino", engine: "1.3 Multijet", yearRange: "2008 - 2015", oemNumber: "0281031679" },
          { brand: "Fiat", model: "Linea", engine: "1.3 Multijet", yearRange: "2007 - 2015", oemNumber: "0281031679" },
        ],
        installationNotes: "Virgin modda gönderilir, araca takıldığında ilk kontak açılışında immobilizer kodunu otomatik öğrenir.",
        featured: true,
        createdAt: now - 4000,
        updatedAt: now - 4000,
      },

      // 8. Mercedes Sprinter ECU
      {
        title: "Mercedes ECU Sprinter 2.2 CDI",
        slug: "a264913312-mercedes-sprinter",
        oemNumber: "A2849133/2",
        boschNumber: "28383921",
        otherNumbers: ["CRD3.10", "A6519000401", "OM651"],
        categorySlug: "motor-beyinleri-ecu",
        categoryName: "Motor Beyinleri (ECU)",
        brand: "Mercedes-Benz",
        model: "Sprinter 2.2 CDI",
        generation: "W906",
        yearRange: "2013 - 2018",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "3 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "128 Pin",
        voltage: "12V",
        weight: "1.35 kg",
        dimensions: "19 x 16 x 4 cm",
        softwareVersion: "CRD3.10",
        hardwareVersion: "A6519000401",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Mercedes Sprinter W906 ve Vito W447 2.2 CDI OM651 motor kontrol ünitesi. Ağır ticari şartlara uygun testlerden geçirilmiştir.",
        images: ["/images/cat-ecu.jpg", "/images/catalog-ecu-banner.jpg"],
        compatibleVehicles: [
          { brand: "Mercedes-Benz", model: "Sprinter W906", engine: "2.2 CDI OM651 (313/316 CDI)", yearRange: "2013 - 2018", oemNumber: "A2849133/2" },
          { brand: "Mercedes-Benz", model: "Vito W447", engine: "2.2 CDI OM651", yearRange: "2014 - 2019", oemNumber: "A2849133/2" },
        ],
        installationNotes: "FBS3 / FBS4 yetkilendirme aktarımı veya klonlama gerektirir.",
        featured: true,
        createdAt: now - 3000,
        updatedAt: now - 3000,
      },

      // 9. VW Golf 1.6 TDI ECU
      {
        title: "VW ECU Golf 1.6 TDI",
        slug: "03g906021qd-vw-golf",
        oemNumber: "03G906021QD",
        boschNumber: "0281013223",
        otherNumbers: ["EDC16U34", "03G906021AN", "1037382098"],
        categorySlug: "motor-beyinleri-ecu",
        categoryName: "Motor Beyinleri (ECU)",
        brand: "Volkswagen",
        model: "Golf 1.6 TDI",
        generation: "Golf 6",
        yearRange: "2009 - 2013",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "3 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "94 Pin",
        voltage: "12V",
        weight: "1.20 kg",
        dimensions: "18 x 16 x 4 cm",
        softwareVersion: "EDC16U34 1037382098",
        hardwareVersion: "03G906021QD",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Bosch EDC16U34 / Continental PCR2.1 uyumlu VW Golf 6, Jetta ve Caddy motor kontrol ünitesi. Orijinal yazılımlı ve tam fonksiyonel.",
        images: ["/images/cat-ecu.jpg", "/images/catalog-ecu-banner.jpg"],
        compatibleVehicles: [
          { brand: "Volkswagen", model: "Golf 6", engine: "1.6 TDI / 1.9 TDI", yearRange: "2009 - 2013", oemNumber: "03G906021QD" },
          { brand: "Volkswagen", model: "Caddy", engine: "1.6 TDI / 1.9 TDI", yearRange: "2008 - 2014", oemNumber: "03G906021QD" },
          { brand: "Volkswagen", model: "Jetta", engine: "1.6 TDI", yearRange: "2009 - 2013", oemNumber: "03G906021QD" },
        ],
        installationNotes: "İmmobilizer kodlama desteği sağlanır.",
        featured: true,
        createdAt: now - 2000,
        updatedAt: now - 2000,
      },

      // 10. ATE MK60 ABS Beyni VW Golf / Passat
      {
        title: "ATE MK60 ABS / ESP Hidrolik Beyin Modülü",
        slug: "1k0907379ce-ate-abs-vw",
        oemNumber: "1K0907379CE",
        boschNumber: "10.0961-0307.3",
        otherNumbers: ["1K0614517BD", "10.0212-0220.4", "ATE-MK60EC1"],
        categorySlug: "abs-esp-beyinleri",
        categoryName: "ABS / ESP Beyinleri",
        brand: "Volkswagen",
        model: "Golf 6 / Passat B7",
        generation: "MK6 / B7",
        yearRange: "2009 - 2015",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "6 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "47 Pin",
        voltage: "12V",
        weight: "2.80 kg",
        dimensions: "20 x 18 x 12 cm",
        softwareVersion: "MK60EC1 H31",
        hardwareVersion: "1K0907379CE",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "ATE MK60EC1 Volkswagen Golf 6, Passat B7, Jetta ve Skoda Octavia ESP hidrolik kontrol bloğu ve elektronik beyni. 01435 basınç sensörü arızası ve valf testleri garantili olarak yapılmıştır.",
        images: ["/images/cat-abs.jpg", "/images/hero-ecu-modules.jpg"],
        compatibleVehicles: [
          { brand: "Volkswagen", model: "Golf 6", engine: "1.4 TSI / 1.6 TDI / 2.0 TDI", yearRange: "2009 - 2013", oemNumber: "1K0907379CE" },
          { brand: "Volkswagen", model: "Passat B7", engine: "1.4 TSI / 1.6 TDI / 2.0 TDI", yearRange: "2010 - 2015", oemNumber: "1K0907379CE" },
          { brand: "Skoda", model: "Octavia A5", engine: "Tüm Motorlar", yearRange: "2009 - 2013", oemNumber: "1K0907379CE" },
        ],
        installationNotes: "Montaj sonrası fren hidrolik havası cihaz ile alınmalı ve direksiyon açı sensörü kalibrasyonu yapılmalıdır.",
        featured: true,
        createdAt: now - 1000,
        updatedAt: now - 1000,
      },

      // 11. BMW E90 Bosch 8.0 ESP ABS Modülü
      {
        title: "Bosch 8.0 ABS / ESP Modülü BMW E90",
        slug: "34516776057-bmw-e90-abs",
        oemNumber: "34516776057",
        boschNumber: "0265950067",
        otherNumbers: ["34516776058", "0265230043", "DSC-8.0"],
        categorySlug: "abs-esp-beyinleri",
        categoryName: "ABS / ESP Beyinleri",
        brand: "BMW",
        model: "3 Serisi E90 / E91 / E92",
        generation: "E90 LCI",
        yearRange: "2007 - 2012",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "6 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "38 Pin",
        voltage: "12V",
        weight: "3.10 kg",
        dimensions: "22 x 18 x 14 cm",
        softwareVersion: "DSC 8.0",
        hardwareVersion: "0265950067",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Bosch 8.0 DSC / ESP Fren Hidrolik Pompası ve Beyni, BMW E90 320d, 320i ve 1 Serisi E87 araçlar için orijinal test edilmiş modüldür. Hidrolik motor ve basınç valfleri yenilenmiştir.",
        images: ["/images/cat-abs.jpg", "/images/hero-ecu-modules.jpg"],
        compatibleVehicles: [
          { brand: "BMW", model: "3 Serisi E90", engine: "320d / 320i / 325d", yearRange: "2007 - 2012", oemNumber: "34516776057" },
          { brand: "BMW", model: "1 Serisi E87", engine: "116i / 118d / 120d", yearRange: "2007 - 2011", oemNumber: "34516776057" },
        ],
        installationNotes: "VIN kodlama ve ISTA üzerinden fren havası indirme prosedürü uygulanmalıdır.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },

      // 12. Autoliv Airbag Beyni Renault Clio 4
      {
        title: "Autoliv Airbag Kontrol Beyni Renault Clio 4",
        slug: "985101389r-renault-clio4-airbag",
        oemNumber: "985101389R",
        boschNumber: "620580900",
        otherNumbers: ["985100475R", "A2C80612900", "AUTOLIV-RC7"],
        categorySlug: "airbag-beyinleri",
        categoryName: "Airbag Beyinleri",
        brand: "Renault",
        model: "Clio 4 / Captur",
        generation: "Clio 4",
        yearRange: "2012 - 2019",
        fuelType: "Dizel",
        condition: "Sıfırlanmış - Virgin",
        warranty: "1 Yıl Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "56 Pin",
        voltage: "12V",
        weight: "0.45 kg",
        dimensions: "12 x 10 x 3 cm",
        softwareVersion: "AUTOLIV RC7",
        hardwareVersion: "985101389R",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Renault Clio 4 ve Captur Autoliv Airbag Beyni. Kaza sonrası çarpışma verisi (Crash Data) özel laboratuvar cihazlarımızla silinmiş ve fabrika sıfır (Virgin) konumuna getirilmiştir.",
        images: ["/images/cat-airbag.jpg", "/images/hero-ecu-modules.jpg"],
        compatibleVehicles: [
          { brand: "Renault", model: "Clio 4", engine: "0.9 TCe / 1.2 / 1.5 dCi", yearRange: "2012 - 2019", oemNumber: "985101389R" },
          { brand: "Renault", model: "Captur", engine: "0.9 TCe / 1.2 TCe / 1.5 dCi", yearRange: "2013 - 2019", oemNumber: "985101389R" },
        ],
        installationNotes: "Montaj esnasında akü kutup başı mutlaka sökük olmalı ve airbag tüpleri sağlam olmalıdır.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },

      // 13. VW Golf 6 BCM Gövde Modülü
      {
        title: "Continental BCM Gövde Kontrol Beyni VW Golf 6",
        slug: "1k0937087ql-vw-bcm",
        oemNumber: "1K0937087QL",
        boschNumber: "5DK010055-61",
        otherNumbers: ["1K0937087AN", "1K0937087H", "BCM-PQ35"],
        categorySlug: "bcm-bsi-sam-modulleri",
        categoryName: "BCM / BSI Beyinleri",
        brand: "Volkswagen",
        model: "Golf 6 / Jetta 6 / Scirocco",
        generation: "PQ35",
        yearRange: "2010 - 2015",
        fuelType: "Benzin",
        condition: "Çıkma - Orijinal",
        warranty: "6 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "156 Pin (3 Büyük Soket)",
        voltage: "12V",
        weight: "0.85 kg",
        dimensions: "22 x 16 x 5 cm",
        softwareVersion: "SW 0651",
        hardwareVersion: "HW 028",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Continental BCM PQ35 Yüksek Donanım (Highline) Gövde Kontrol Modülü. Xenon/LED far, ayak aydınlatması, alarm ve merkezi kilit fonksiyonları tam destekli.",
        images: ["/images/cat-bcm.jpg", "/images/cat-uch.jpg"],
        compatibleVehicles: [
          { brand: "Volkswagen", model: "Golf 6", engine: "Tüm Motorlar", yearRange: "2009 - 2013", oemNumber: "1K0937087QL" },
          { brand: "Volkswagen", model: "Jetta 6", engine: "Tüm Motorlar", yearRange: "2011 - 2016", oemNumber: "1K0937087QL" },
          { brand: "Volkswagen", model: "Scirocco", engine: "1.4 TSI / 2.0 TSI", yearRange: "2010 - 2015", oemNumber: "1K0937087QL" },
        ],
        installationNotes: "VCDS veya ODIS ile eski beynin uzun kodlaması (Long Coding) aktarılmalıdır.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },

      // 14. Mercedes Ön SAM Modülü W204
      {
        title: "Mercedes Ön SAM Sigorta & Röle Kontrol Modülü",
        slug: "a2049005901-mercedes-sam",
        oemNumber: "A2049005901",
        boschNumber: "5DK009491-00",
        otherNumbers: ["A2045400150", "A2049000101", "SAM-FRONT"],
        categorySlug: "uch-sam-modulleri",
        categoryName: "UCH / SAM Modülleri",
        brand: "Mercedes-Benz",
        model: "C-Class W204 / E-Class W212",
        generation: "W204 / X204",
        yearRange: "2008 - 2014",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "6 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "Çoklu Soket Grubu",
        voltage: "12V",
        weight: "1.40 kg",
        dimensions: "26 x 20 x 8 cm",
        softwareVersion: "SAMF_204",
        hardwareVersion: "A2049005901",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Mercedes W204 ve GLK X204 Ön SAM Elektronik Sigorta ve Röle Dağıtım Ünitesi. Silecek, far yıkama, korna ve aydınlatma röle devreleri test edilmiştir.",
        images: ["/images/cat-uch.jpg", "/images/cat-bcm.jpg"],
        compatibleVehicles: [
          { brand: "Mercedes-Benz", model: "C-Serisi W204", engine: "C180 / C200 / C220 CDI", yearRange: "2008 - 2014", oemNumber: "A2049005901" },
          { brand: "Mercedes-Benz", model: "GLK X204", engine: "200 CDI / 220 CDI / 250 CDI", yearRange: "2008 - 2015", oemNumber: "A2049005901" },
        ],
        installationNotes: "Doğrudan soket sokete montaj yapılabilir.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },

      // 15. Delphi BSM L04 Sigorta Kutusu Peugeot / Citroen
      {
        title: "Delphi BSM L04 Motor Sigorta Dağıtım Kutusu",
        slug: "9657718580-peugeot-bsm",
        oemNumber: "9657718580",
        boschNumber: "BSM-L04-00",
        otherNumbers: ["9657718780", "6500CK", "6500FH"],
        categorySlug: "sigorta-kutulari",
        categoryName: "Sigorta Kutuları",
        brand: "Peugeot",
        model: "307 / 206 / Citroen C4",
        generation: "T5 / T6",
        yearRange: "2004 - 2010",
        fuelType: "Dizel",
        condition: "Sıfır - Orijinal",
        warranty: "1 Yıl Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "5 Renkli Soket",
        voltage: "12V",
        weight: "0.95 kg",
        dimensions: "24 x 16 x 7 cm",
        softwareVersion: "BSM L04",
        hardwareVersion: "9657718580",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Peugeot 307, 206+, Partner ve Citroen C4 1.6 HDi / 1.6 16V motor içi BSM L04 sigorta tablası. Yakıt pompası ve korna rölesi sorunlarına kesin çözüm.",
        images: ["/images/cat-fusebox.jpg", "/images/cat-bcm.jpg"],
        compatibleVehicles: [
          { brand: "Peugeot", model: "307", engine: "1.4 HDi / 1.6 HDi / 1.6 16V", yearRange: "2004 - 2008", oemNumber: "9657718580" },
          { brand: "Peugeot", model: "Partner", engine: "1.6 HDi", yearRange: "2005 - 2011", oemNumber: "9657718580" },
          { brand: "Citroën", model: "C4", engine: "1.6 HDi / 1.6 16V", yearRange: "2004 - 2010", oemNumber: "9657718580" },
        ],
        installationNotes: "Kodlama gerektirmez, tak-çalıştır üründür.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },

      // 16. DSG 7 İleri DQ200 0AM Mekatronik Şanzıman Beyni
      {
        title: "DSG 7 İleri DQ200 0AM Mekatronik Şanzıman Beyni",
        slug: "0am927769d-dsg-tcu",
        oemNumber: "0AM927769D",
        boschNumber: "0AM325025D",
        otherNumbers: ["0AM927769K", "0AM927769G", "DQ200-TCU"],
        categorySlug: "sanziman-beyinleri",
        categoryName: "Şanzıman Beyinleri",
        brand: "Volkswagen",
        model: "Golf 7 / Passat B8 / Polo",
        generation: "DQ200",
        yearRange: "2010 - 2020",
        fuelType: "Benzin",
        condition: "Revizyonlu - Testli",
        warranty: "6 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "25 Pin Mekatronik Soket",
        voltage: "12V",
        weight: "1.80 kg",
        dimensions: "24 x 18 x 6 cm",
        softwareVersion: "0AM DQ200 VAG",
        hardwareVersion: "0AM927769D",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Volkswagen, Audi, Seat ve Skoda kuru kavrama 7 ileri DSG DQ200 mekatronik kontrol kartı ve valf beyni. Basınç kaybı, P17BF ve P189C arızalarına karşı güçlendirilmiş versiyondur.",
        images: ["/images/cat-transmission.jpg", "/images/hero-ecu-modules.jpg"],
        compatibleVehicles: [
          { brand: "Volkswagen", model: "Golf 7 / Passat B8 / Polo", engine: "1.0 TSI / 1.2 TSI / 1.4 TSI / 1.6 TDI", yearRange: "2012 - 2020", oemNumber: "0AM927769D" },
          { brand: "Audi", model: "A3 8V", engine: "1.4 TFSI / 1.6 TDI", yearRange: "2013 - 2020", oemNumber: "0AM927769D" },
          { brand: "Seat", model: "Leon 5F", engine: "1.2 TSI / 1.4 TSI / 1.6 TDI", yearRange: "2013 - 2020", oemNumber: "0AM927769D" },
          { brand: "Skoda", model: "Octavia 3", engine: "1.2 TSI / 1.4 TSI / 1.6 TDI", yearRange: "2013 - 2020", oemNumber: "0AM927769D" },
        ],
        installationNotes: "Aracın şasi numarasına ve şanzıman koduna uygun yazılım yüklenerek gönderilir. Montaj sonrası temel ayar (Basic Setting) yapılmalıdır.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },

      // 17. Mercedes 7G-Tronic 722.9 VGS3 Şanzıman Beyni
      {
        title: "Mercedes 7G-Tronic 722.9 VGS3 Şanzıman Beyni",
        slug: "a0034460310-mercedes-7g-tronic",
        oemNumber: "A0034460310",
        boschNumber: "Continental VGS3",
        otherNumbers: ["A0335457332", "A0002701700", "VGS3-NAG2"],
        categorySlug: "sanziman-beyinleri",
        categoryName: "Şanzıman Beyinleri",
        brand: "Mercedes-Benz",
        model: "C / E / S / ML / CLS Serisi",
        generation: "722.9",
        yearRange: "2008 - 2017",
        fuelType: "Dizel",
        condition: "Sıfırlanmış - Virgin",
        warranty: "1 Yıl Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "Özel Şanzıman Soketi",
        voltage: "12V",
        weight: "0.60 kg",
        dimensions: "18 x 14 x 4 cm",
        softwareVersion: "VGS3 NAG2",
        hardwareVersion: "A0034460310",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Mercedes 7G-Tronic 722.9 otomatik şanzıman iletken plaka ve VGS3 mekatronik beyni. Hız sensörü (Y3/8n1, Y3/8n2) arızaları giderilmiş ve virginlenmiş ünitedir.",
        images: ["/images/cat-transmission.jpg", "/images/hero-ecu-modules.jpg"],
        compatibleVehicles: [
          { brand: "Mercedes-Benz", model: "C-Serisi W204", engine: "722.9 7-Gtronic", yearRange: "2008 - 2014", oemNumber: "A0034460310" },
          { brand: "Mercedes-Benz", model: "E-Serisi W212", engine: "722.9 7-Gtronic", yearRange: "2009 - 2016", oemNumber: "A0034460310" },
          { brand: "Mercedes-Benz", model: "ML W164 / W166", engine: "722.9 7-Gtronic", yearRange: "2008 - 2016", oemNumber: "A0034460310" },
        ],
        installationNotes: "Virginlenmiş olarak gönderilir. Xentry / Vediamo ile SCN kodlama ve vites adaptasyonu uygulanmalıdır.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },

      // 18. VDO Kadran VW Passat B7
      {
        title: "VDO Dijital Gösterge Paneli Kadran VW Passat B7",
        slug: "3aa920870a-vw-passat-kadran",
        oemNumber: "3AA920870A",
        boschNumber: "A2C53381480",
        otherNumbers: ["3AA920870", "VDO-NEC24C64", "PASSAT-COLOR"],
        categorySlug: "gosterge-panelleri",
        categoryName: "Gösterge Panelleri",
        brand: "Volkswagen",
        model: "Passat B7 / CC",
        generation: "B7",
        yearRange: "2011 - 2015",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "6 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "32 Pin Mavi Soket",
        voltage: "12V",
        weight: "1.10 kg",
        dimensions: "36 x 18 x 12 cm",
        softwareVersion: "SW 0705",
        hardwareVersion: "HW 04",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Volkswagen Passat B7 ve Passat CC renkli ekranlı (MFA Premium) VDO gösterge tablosu. İbre motorları, LED aydınlatmalar ve LCD ekranı hatasızdır.",
        images: ["/images/cat-cluster.jpg", "/images/hero-ecu-modules.jpg"],
        compatibleVehicles: [
          { brand: "Volkswagen", model: "Passat B7", engine: "1.6 TDI / 2.0 TDI / 1.4 TSI", yearRange: "2011 - 2015", oemNumber: "3AA920870A" },
          { brand: "Volkswagen", model: "Passat CC", engine: "Tüm Motorlar", yearRange: "2010 - 2016", oemNumber: "3AA920870A" },
        ],
        installationNotes: "İmmobilizer eşleştirmesi veya klonlama gerektirir.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },

      // 19. VW Direksiyon Sargısı & Açı Sensörü
      {
        title: "VW Direksiyon Açı Sensörü & Zemberek Modülü",
        slug: "1k0953549ch-vw-direksiyon-modulu",
        oemNumber: "1K0953549CH",
        boschNumber: "1K0959653C",
        otherNumbers: ["1K0953549CD", "1K0953549BK", "SLIP-RING"],
        categorySlug: "direksiyon-kumanda-modulleri",
        categoryName: "Direksiyon Kumanda Modülleri",
        brand: "Volkswagen",
        model: "Golf 5 / 6 / Passat / Caddy",
        generation: "PQ35",
        yearRange: "2006 - 2015",
        fuelType: "Benzin",
        condition: "Sıfır - Orijinal",
        warranty: "1 Yıl Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "Direksiyon Kol Grubu",
        voltage: "12V",
        weight: "0.55 kg",
        dimensions: "18 x 16 x 10 cm",
        softwareVersion: "Highline CH",
        hardwareVersion: "1K0953549CH",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Volkswagen Golf, Jetta, Caddy, Tiguan ve Scirocco Highline Direksiyon Açı Sensör Modülü. Hız sabitleyici (Cruise Control) ve fonksiyonel direksiyon tuşlarını tam destekler.",
        images: ["/images/cat-steering.jpg", "/images/hero-ecu-modules.jpg"],
        compatibleVehicles: [
          { brand: "Volkswagen", model: "Golf 5 / 6", engine: "Tüm Motorlar", yearRange: "2006 - 2013", oemNumber: "1K0953549CH" },
          { brand: "Volkswagen", model: "Caddy", engine: "Tüm Motorlar", yearRange: "2007 - 2015", oemNumber: "1K0953549CH" },
          { brand: "Volkswagen", model: "Jetta", engine: "Tüm Motorlar", yearRange: "2006 - 2014", oemNumber: "1K0953549CH" },
        ],
        installationNotes: "Montaj sonrası VCDS ile direksiyon açı sensörü (G85) temel ayarı yapılmalıdır.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },

      // 20. Denso Dijital Klima Paneli Toyota
      {
        title: "Denso Dijital Klima Kontrol Paneli Toyota Corolla",
        slug: "55900-02550-toyota-corolla-klima",
        oemNumber: "55900-02550",
        boschNumber: "146570-8450",
        otherNumbers: ["5590002550", "DENSO-AC", "COROLLA-AC"],
        categorySlug: "klima-kontrol-uniteleri",
        categoryName: "Klima Kontrol Üniteleri",
        brand: "Toyota",
        model: "Corolla / Auris",
        generation: "E140 / E150",
        yearRange: "2007 - 2013",
        fuelType: "Dizel",
        condition: "Çıkma - Orijinal",
        warranty: "6 Ay Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "26 Pin",
        voltage: "12V",
        weight: "0.65 kg",
        dimensions: "22 x 12 x 8 cm",
        softwareVersion: "DENSO CLIMATE",
        hardwareVersion: "55900-02550",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Toyota Corolla ve Auris dijital çift bölgeli otomatik klima kontrol paneli. Döner düğmeler, dijital ekran aydınlatması ve flap motor çıkışları test edilmiştir.",
        images: ["/images/cat-climate.jpg", "/images/hero-ecu-modules.jpg"],
        compatibleVehicles: [
          { brand: "Toyota", model: "Corolla", engine: "1.4 D-4D / 1.6 Dual VVT-i", yearRange: "2007 - 2013", oemNumber: "55900-02550" },
          { brand: "Toyota", model: "Auris", engine: "1.4 D-4D / 1.6", yearRange: "2007 - 2012", oemNumber: "55900-02550" },
        ],
        installationNotes: "Soketi takıldığı anda çalışır, kodlama gerektirmez.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },

      // 21. VW MIB2 Multimedya Ekran Ünitesi
      {
        title: "VW MIB2 Composition Media Dokunmatik Multimedya",
        slug: "5g0035819a-vw-mib2-multimedya",
        oemNumber: "5G0035819A",
        boschNumber: "5G0919605D",
        otherNumbers: ["3Q0035819A", "MIB2-STD", "CARPLAY-UNIT"],
        categorySlug: "multimedya-uniteleri",
        categoryName: "Multimedya Üniteleri",
        brand: "Volkswagen",
        model: "Golf 7 / Passat B8",
        generation: "MIB2",
        yearRange: "2015 - 2020",
        fuelType: "Benzin",
        condition: "Sıfır - Orijinal",
        warranty: "1 Yıl Garanti",
        tested: true,
        plugAndPlay: true,
        pinCount: "Quadlock Soket",
        voltage: "12V",
        weight: "1.90 kg",
        dimensions: "26 x 18 x 14 cm",
        softwareVersion: "MST2_EU_VW_P0879D",
        hardwareVersion: "5G0035819A",
        inStock: true,
        priceText: "Fiyat Sorunuz",
        description: "Volkswagen Golf 7, Passat B8 ve Tiguan MIB2 Dokunmatik Multimedya Ünitesi. Apple CarPlay, Android Auto, Bluetooth ve geri görüş kamerası aktivasyonu açık olarak teslim edilir.",
        images: ["/images/cat-multimedia.jpg", "/images/hero-ecu-modules.jpg"],
        compatibleVehicles: [
          { brand: "Volkswagen", model: "Golf 7", engine: "Tüm Motorlar", yearRange: "2013 - 2020", oemNumber: "5G0035819A" },
          { brand: "Volkswagen", model: "Passat B8", engine: "Tüm Motorlar", yearRange: "2015 - 2020", oemNumber: "5G0035819A" },
          { brand: "Volkswagen", model: "Tiguan", engine: "Tüm Motorlar", yearRange: "2016 - 2021", oemNumber: "5G0035819A" },
        ],
        installationNotes: "Bileşen koruması (Component Protection) kaldırılmış olarak gönderilir, tak-çalıştır konumdadır.",
        featured: true,
        createdAt: now,
        updatedAt: now,
      },
    ];

    for (const p of realInventory) {
      await ctx.db.insert("products", p);
    }

    return {
      success: true,
      categoriesCount: categoriesList.length,
      brandsCount: brandList.length,
      productsCount: realInventory.length,
    };
  },
});
